---
- name: System Health Cheack and report save to Geylang Linux Ansible Servers.
  hosts: all
  become: true
  tasks:
    - name: Health check script Transfer to the client location.
      copy:
        src: /home/ansible/playbooks/RDC/Linux_Patch/Linux_health_check_v1.sh
        dest: /tmp
        owner: root
        group: root
        mode: '0777'
    - name: execute a script in linux
      shell: /bin/sh /tmp/Linux_health_check_v1.sh
      register: file_name

#    - name: check and verify log file
#      shell: ls /tmp/myhealth_$(hostname)*.txt
#      register: files_to_copy

    - name: Transfer log file to the ansible server.
      fetch:
        src: "{{ item }}"
        dest: /home/ansible/playbooks/RDC/Linux_Patch/log/
        flat: true
      with_items: "{{file_name.stdout}}"
