---
- name: Playbook to create user and and sudo passwordless entry
  hosts: all
  tasks:
    - name: create group
      group:
        name: ansible
        state: present

    - name: create user
      user:
        name: ansible
        comment: "ansible user for playbook"
        password: ansible
        state: present
        group: ansible

    - name: add entry in sudoers for passwordless login
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: add user ansible in wheel group
      user:
        name: ansible
        groups: wheel
        append: yes
        state: present
        createhome: yes
